In [1]:
from nba_api.stats.endpoints import leaguegamelog

In [2]:
game_log = leaguegamelog.LeagueGameLog(
    season="2025-26",
    season_type_all_star="Regular Season",
)

df = game_log.get_data_frames()[0]

In [3]:
df.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22025,1610612744,GSW,Golden State Warriors,0022500002,2025-10-21,GSW @ LAL,W,240,38,...,31,40,29,10,4,19,27,119,10,1
1,22025,1610612745,HOU,Houston Rockets,0022500001,2025-10-21,HOU @ OKC,L,290,43,...,36,52,23,6,5,25,26,124,-1,1
2,22025,1610612747,LAL,Los Angeles Lakers,0022500002,2025-10-21,LAL vs. GSW,L,240,42,...,32,39,23,7,2,20,21,109,-10,1
3,22025,1610612760,OKC,Oklahoma City Thunder,0022500001,2025-10-21,OKC vs. HOU,W,290,46,...,27,38,29,12,4,12,27,125,1,1
4,22025,1610612737,ATL,Atlanta Hawks,0022500082,2025-10-22,ATL vs. TOR,L,240,38,...,26,34,25,7,6,16,24,118,-20,1

In [4]:
df[[
    "GAME_ID",
    "GAME_DATE",
    "TEAM_ABBREVIATION",
    "MATCHUP",
    "WL",
    "PTS",
    "PLUS_MINUS",
]].head(10)

      GAME_ID   GAME_DATE TEAM_ABBREVIATION      MATCHUP WL  PTS  PLUS_MINUS
0  0022500002  2025-10-21               GSW    GSW @ LAL  W  119          10
1  0022500001  2025-10-21               HOU    HOU @ OKC  L  124          -1
2  0022500002  2025-10-21               LAL  LAL vs. GSW  L  109         -10
3  0022500001  2025-10-21               OKC  OKC vs. HOU  W  125           1
4  0022500082  2025-10-22               ATL  ATL vs. TOR  L  118         -20
5  0022500083  2025-10-22               BOS  BOS vs. PHI  L  116          -1
6  0022500003  2025-10-22               CLE    CLE @ NYK  L  111          -8
7  0022500085  2025-10-22               NOP    NOP @ MEM  L  122          -6
8  0022500084  2025-10-22               CHI  CHI vs. DET  W  115           4
9  0022500004  2025-10-22               DAL  DAL vs. SAS  L   92         -33