In [1]:
from nba_api.stats.endpoints import leaguegamelog, boxscoretraditionalv3
import pandas as pd
import time

In [2]:
game_log = leaguegamelog.LeagueGameLog(
    season="2025-26",
    season_type_all_star="Regular Season",
)

games_df = game_log.get_data_frames()[0]

In [3]:
game_ids = games_df["GAME_ID"].drop_duplicates().tolist()

In [4]:
len(game_ids)

1230

In [5]:
test_game_ids = game_ids[:10]
test_game_ids

['0022500001',
 '0022500002',
 '0022500087',
 '0022500081',
 '0022500086',
 '0022500089',
 '0022500080',
 '0022500003',
 '0022500083',
 '0022500082']

In [6]:
player_game_dfs = []

for game_id in test_game_ids:
    box = boxscoretraditionalv3.BoxScoreTraditionalV3(
        game_id=game_id
    )

    player_df = box.get_data_frames()[0]

    player_game_dfs.append(player_df)

    time.sleep(0.6)

In [7]:
player_games_df = pd.concat(
    player_game_dfs,
    ignore_index=True
)

In [8]:
player_games_df.shape

(274, 34)

In [9]:
player_games_df.head()

,gameId,teamId,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,...,reboundsOffensive,reboundsDefensive,reboundsTotal,assists,steals,blocks,turnovers,foulsPersonal,points,plusMinusPoints
0,0022500001,1610612760,Oklahoma City,Thunder,OKC,thunder,1629652,Luguentz,Dort,L. Dort,...,2,4,6,5,1,0,1,4,6,2.0
1,0022500001,1610612760,Oklahoma City,Thunder,OKC,thunder,1631096,Chet,Holmgren,C. Holmgren,...,2,5,7,2,0,0,3,6,28,-1.0
2,0022500001,1610612760,Oklahoma City,Thunder,OKC,thunder,1628392,Isaiah,Hartenstein,I. Hartenstein,...,5,3,8,5,2,0,1,6,6,9.0
3,0022500001,1610612760,Oklahoma City,Thunder,OKC,thunder,1641717,Cason,Wallace,C. Wallace,...,1,6,7,5,4,0,2,3,14,8.0
4,0022500001,1610612760,Oklahoma City,Thunder,OKC,thunder,1628983,Shai,Gilgeous-Alexander,S. Gilgeous-Alexander,...,0,5,5,5,2,2,3,2,35,3.0

In [10]:
game_dates = (
    games_df[["GAME_ID", "GAME_DATE"]]
    .drop_duplicates()
    .rename(columns={"GAME_ID": "gameId", "GAME_DATE": "gameDate"})
)

In [11]:
player_games_df = player_games_df.merge(
    game_dates,
    on="gameId",
    how="left"
)

In [14]:
player_games_df.head()

,gameId,teamId,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,...,reboundsDefensive,reboundsTotal,assists,steals,blocks,turnovers,foulsPersonal,points,plusMinusPoints,gameDate
0,0022500001,1610612760,Oklahoma City,Thunder,OKC,thunder,1629652,Luguentz,Dort,L. Dort,...,4,6,5,1,0,1,4,6,2.0,2025-10-21
1,0022500001,1610612760,Oklahoma City,Thunder,OKC,thunder,1631096,Chet,Holmgren,C. Holmgren,...,5,7,2,0,0,3,6,28,-1.0,2025-10-21
2,0022500001,1610612760,Oklahoma City,Thunder,OKC,thunder,1628392,Isaiah,Hartenstein,I. Hartenstein,...,3,8,5,2,0,1,6,6,9.0,2025-10-21
3,0022500001,1610612760,Oklahoma City,Thunder,OKC,thunder,1641717,Cason,Wallace,C. Wallace,...,6,7,5,4,0,2,3,14,8.0,2025-10-21
4,0022500001,1610612760,Oklahoma City,Thunder,OKC,thunder,1628983,Shai,Gilgeous-Alexander,S. Gilgeous-Alexander,...,5,5,5,2,2,3,2,35,3.0,2025-10-21

In [13]:
player_games_df["gameDate"] = pd.to_datetime(
    player_games_df["gameDate"]
)